"""Conjecture E — Layer 1: consistency scan (F5 vs BDG-style actions).

Goal (per `理论体系/推论核查与验证优先级分析.md` §4.1):
  - Compute BD/BDG-like actions on the same (N, rep) matched dataset,
  - Compare their induced orderings to the current unified functional (F5),
  - Quantify Lorentzian-vs-KR win rates per N and scan coupling λ.

Inputs:
  - outputs_unified_functional/raw_features.csv
  - outputs_unified_functional/bd_actions.csv  (generated by conjecture_e_layer1_bdg_report.py)

Outputs:
  - outputs_unified_functional/conjecture_e_layer1_consistency.csv
"""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass(frozen=True)
class Row:
    family: str
    N: int
    rep: int
    log_H: float
    f5: float
    bdg_d2_link_norm: float
    bdg_d2_corrected_norm: float
    bdg_d4_standard_norm: float
    bd_d4_trunc_norm: float
    bd_ratio: float


ACTION_FIELDS = [
    "bdg_d2_link_norm",
    "bdg_d2_corrected_norm",
    "bdg_d4_standard_norm",
    "bd_d4_trunc_norm",
]


def load_rows(bd_actions_path: Path) -> list[Row]:
    rows = list(csv.DictReader(bd_actions_path.open("r", encoding="utf-8")))
    out: list[Row] = []
    for r in rows:
        out.append(
            Row(
                family=str(r["family"]),
                N=int(r["N"]),
                rep=int(r["rep"]),
                log_H=float(r["log_H"]),
                f5=float(r["f5_calibrated"]),
                bdg_d2_link_norm=float(r["bdg_d2_link_norm"]),
                bdg_d2_corrected_norm=float(r["bdg_d2_corrected_norm"]),
                bdg_d4_standard_norm=float(r["bdg_d4_standard_norm"]),
                bd_d4_trunc_norm=float(r["bd_d4_trunc_norm"]),
                bd_ratio=float(r["bd_ratio"]),
            )
        )
    return out


def score_with_action(row: Row, *, beta_entropy: float, lam: float, action_field: str) -> float:
    raise RuntimeError("Use score_with_action_signed()")


def score_with_action_signed(
    row: Row,
    *,
    beta_entropy: float,
    entropy_sign: float,
    lam: float,
    action_sign: float,
    action_field: str,
) -> float:
    s = float(getattr(row, action_field))
    return entropy_sign * beta_entropy * float(row.log_H) + action_sign * lam * s


def safe_div(a: float, b: float) -> float:
    return a / b if abs(b) > 1e-12 else float("nan")


def crossing_lambda(mean_logh_a: float, mean_s_a: float, mean_logh_b: float, mean_s_b: float, *, beta_entropy: float) -> float:
    raise RuntimeError("Use crossing_lambda_signed()")


def crossing_lambda_signed(
    mean_logh_a: float,
    mean_s_a: float,
    mean_logh_b: float,
    mean_s_b: float,
    *,
    beta_entropy: float,
    entropy_sign: float,
    action_sign: float,
) -> float:
    """Solve λ for equality of mean scores:

      entropy_sign * β logH + action_sign * λ s
    """
    # entropy_sign * β (logH_a - logH_b) + action_sign * λ (s_a - s_b) = 0
    num = -entropy_sign * beta_entropy * (mean_logh_a - mean_logh_b)
    den = action_sign * (mean_s_a - mean_s_b)
    return safe_div(num, den)


def win_rate(rows_a: list[float], rows_b: list[float]) -> float:
    if not rows_a or not rows_b:
        return float("nan")
    m = min(len(rows_a), len(rows_b))
    wins = sum(1 for i in range(m) if rows_a[i] < rows_b[i])
    return wins / float(m)


def agreement_rate(a: list[float], b: list[float], c: list[float], d: list[float]) -> float:
    """Agreement of pairwise comparisons (a<b) vs (c<d) over matched indices."""
    if not a or not b or not c or not d:
        return float("nan")
    m = min(len(a), len(b), len(c), len(d))
    agree = 0
    for i in range(m):
        agree += int((a[i] < b[i]) == (c[i] < d[i]))
    return agree / float(m)


def main() -> int:
    ap = argparse.ArgumentParser(description="Conjecture E layer-1: per-N consistency scan")
    ap.add_argument("--bd-actions", default="outputs_unified_functional/bd_actions.csv")
    ap.add_argument("--out", default="outputs_unified_functional/conjecture_e_layer1_consistency.csv")
    ap.add_argument("--beta-entropy", type=float, default=1.0)
    ap.add_argument("--entropy-sign", type=float, default=-1.0, choices=[-1.0, 1.0], help="use -1 for entropy-dominance convention")
    ap.add_argument("--action-sign", type=float, default=1.0, choices=[-1.0, 1.0], help="use +1 if smaller action is favored")
    ap.add_argument("--lambda-min", type=float, default=0.0)
    ap.add_argument("--lambda-max", type=float, default=20.0)
    ap.add_argument("--lambda-step", type=float, default=1.0)
    ap.add_argument("--families", nargs="*", default=["Lor2D", "Lor3D", "Lor4D", "Lor5D", "KR_like"])
    ap.add_argument("--focus-lor", default="Lor2D", help="Lorentzian family to compare against KR_like")
    args = ap.parse_args()

    bd_path = Path(args.bd_actions)
    if not bd_path.exists():
        raise FileNotFoundError(f"Missing {bd_path}. Run `python conjecture_e_layer1_bdg_report.py` first.")

    rows = load_rows(bd_path)
    families = set(args.families)
    rows = [r for r in rows if r.family in families]

    focus_lor = str(args.focus_lor)
    if focus_lor not in families:
        raise ValueError(f"--focus-lor={focus_lor} not in --families")
    if "KR_like" not in families:
        raise ValueError("KR_like must be included in --families")

    ns = sorted({r.N for r in rows})
    lams = np.arange(args.lambda_min, args.lambda_max + 1e-12, args.lambda_step, dtype=float).tolist()

    # index rows by (family, N, rep)
    by_key: dict[tuple[str, int, int], Row] = {(r.family, r.N, r.rep): r for r in rows}

    # Determine reps present for each N (intersection across selected families)
    reps_by_n: dict[int, list[int]] = {}
    for n in ns:
        reps_sets = []
        for fam in families:
            reps = {r.rep for r in rows if r.N == n and r.family == fam}
            reps_sets.append(reps)
        common = set.intersection(*reps_sets) if reps_sets else set()
        reps_by_n[n] = sorted(common)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        fieldnames = [
            "N",
            "lambda",
            "action_field",
            "beta_entropy",
            "entropy_sign",
            "action_sign",
            "focus_lor",
            "mean_score_focus",
            "mean_score_kr",
            "win_rate_focus_vs_kr",
            "lambda_cross_mean_focus_vs_kr",
            "mean_f5_focus",
            "mean_f5_kr",
            "win_rate_f5_focus_vs_kr",
            "agreement_rate_score_vs_f5",
        ]
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()

        print("=" * 80)
        print("CONJECTURE E - LAYER 1 CONSISTENCY SCAN")
        print("=" * 80)
        print(f"Families: {sorted(families)}")
        print(f"Focus: {focus_lor} vs KR_like")
        print(f"beta_entropy: {args.beta_entropy:g} | entropy_sign: {args.entropy_sign:+g} | action_sign: {args.action_sign:+g}")
        print(f"lambda grid: {lams[0]:g}..{lams[-1]:g} step {args.lambda_step:g}")

        for action_field in ACTION_FIELDS:
            print("\n" + "-" * 80)
            print(f"Action: {action_field}")
            print("-" * 80)

            for n in ns:
                reps = reps_by_n[n]
                if not reps:
                    continue

                focus_rows = [by_key[(focus_lor, n, rep)] for rep in reps]
                kr_rows = [by_key[("KR_like", n, rep)] for rep in reps]

                mean_logh_focus = float(np.mean([r.log_H for r in focus_rows]))
                mean_logh_kr = float(np.mean([r.log_H for r in kr_rows]))
                mean_s_focus = float(np.mean([getattr(r, action_field) for r in focus_rows]))
                mean_s_kr = float(np.mean([getattr(r, action_field) for r in kr_rows]))
                lam_cross = crossing_lambda_signed(
                    mean_logh_focus,
                    mean_s_focus,
                    mean_logh_kr,
                    mean_s_kr,
                    beta_entropy=float(args.beta_entropy),
                    entropy_sign=float(args.entropy_sign),
                    action_sign=float(args.action_sign),
                )

                # F5 baseline at this N (no λ)
                f5_focus = [r.f5 for r in focus_rows]
                f5_kr = [r.f5 for r in kr_rows]
                win_f5 = win_rate(f5_focus, f5_kr)

                # Scan λ
                for lam in lams:
                    scores_focus = [
                        score_with_action_signed(
                            r,
                            beta_entropy=args.beta_entropy,
                            entropy_sign=args.entropy_sign,
                            lam=float(lam),
                            action_sign=args.action_sign,
                            action_field=action_field,
                        )
                        for r in focus_rows
                    ]
                    scores_kr = [
                        score_with_action_signed(
                            r,
                            beta_entropy=args.beta_entropy,
                            entropy_sign=args.entropy_sign,
                            lam=float(lam),
                            action_sign=args.action_sign,
                            action_field=action_field,
                        )
                        for r in kr_rows
                    ]

                    mean_focus = float(np.mean(scores_focus))
                    mean_kr = float(np.mean(scores_kr))
                    win = win_rate(scores_focus, scores_kr)
                    agree = agreement_rate(scores_focus, scores_kr, f5_focus, f5_kr)

                    w.writerow(
                        {
                            "N": n,
                            "lambda": float(lam),
                            "action_field": action_field,
                            "beta_entropy": float(args.beta_entropy),
                            "entropy_sign": float(args.entropy_sign),
                            "action_sign": float(args.action_sign),
                            "focus_lor": focus_lor,
                            "mean_score_focus": mean_focus,
                            "mean_score_kr": mean_kr,
                            "win_rate_focus_vs_kr": win,
                            "lambda_cross_mean_focus_vs_kr": lam_cross,
                            "mean_f5_focus": float(np.mean(f5_focus)),
                            "mean_f5_kr": float(np.mean(f5_kr)),
                            "win_rate_f5_focus_vs_kr": win_f5,
                            "agreement_rate_score_vs_f5": agree,
                        }
                    )

                # Print a compact line for this N: cross + two anchor λ points
                anchor_lams = [lams[0], lams[len(lams) // 2], lams[-1]]
                anchor_stats = []
                for lam in anchor_lams:
                    scores_focus = [
                        score_with_action_signed(
                            r,
                            beta_entropy=args.beta_entropy,
                            entropy_sign=args.entropy_sign,
                            lam=float(lam),
                            action_sign=args.action_sign,
                            action_field=action_field,
                        )
                        for r in focus_rows
                    ]
                    scores_kr = [
                        score_with_action_signed(
                            r,
                            beta_entropy=args.beta_entropy,
                            entropy_sign=args.entropy_sign,
                            lam=float(lam),
                            action_sign=args.action_sign,
                            action_field=action_field,
                        )
                        for r in kr_rows
                    ]
                    anchor_stats.append(f"lam={lam:g}:win={win_rate(scores_focus, scores_kr):.2f}")
                lam_cross_s = "nan" if math.isnan(lam_cross) else f"{lam_cross:.2f}"
                print(
                    f"N={n:>3d} reps={len(reps):>2d} | logH({focus_lor},{mean_logh_focus:.2f}) vs KR({mean_logh_kr:.2f})"
                    f" | mean_s({mean_s_focus:+.3f} vs {mean_s_kr:+.3f}) | lambda_cross~{lam_cross_s}"
                    f" | F5_win={win_f5:.2f} | {' '.join(anchor_stats)}"
                )

    print(f"\nSaved: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
