"""Conjecture E - Bridge fit between F5 and BD/BDG observables.

This script closes the current layer-1 output into a layer-3 bridge test:

  - Does adding a BD/BDG-like scalar to F5 improve Lorentzian-vs-KR ordering?
  - Which BD-like observable provides the strongest bridge?
  - Is the best coupling O(1) across N?

Inputs:
  - outputs_unified_functional/bd_actions.csv
    (generated by conjecture_e_layer1_bdg_report.py)

Outputs:
  - outputs_unified_functional/conjecture_e_bridge_fit.csv
  - outputs_unified_functional/conjecture_e_bridge_fit.md
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np


def load_rows(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def spearman_rank(x: np.ndarray, y: np.ndarray) -> float:
    if x.size != y.size or x.size == 0:
        return float("nan")

    def rankdata(a: np.ndarray) -> np.ndarray:
        order = np.argsort(a, kind="mergesort")
        ranks = np.empty_like(order, dtype=float)
        ranks[order] = np.arange(1, a.size + 1, dtype=float)
        sorted_a = a[order]
        i = 0
        while i < a.size:
            j = i + 1
            while j < a.size and sorted_a[j] == sorted_a[i]:
                j += 1
            if j - i > 1:
                ranks[order[i:j]] = (i + 1 + j) / 2.0
            i = j
        return ranks

    rx = rankdata(x)
    ry = rankdata(y)
    rx -= rx.mean()
    ry -= ry.mean()
    denom = float(np.sqrt(np.sum(rx * rx) * np.sum(ry * ry)))
    return float(np.sum(rx * ry) / denom) if denom > 0 else float("nan")


def hit_rate(focus_scores: list[float], kr_scores: list[float]) -> float:
    m = min(len(focus_scores), len(kr_scores))
    if m == 0:
        return float("nan")
    wins = sum(1 for i in range(m) if focus_scores[i] < kr_scores[i])
    return wins / float(m)


def scan_lambda(
    rows: list[dict],
    action_key: str,
    focus_family: str = "Lor4D",
    control_family: str = "KR_like",
    beta_entropy: float = 1.0,
    entropy_sign: float = -1.0,
    action_sign: float = -1.0,
    lambdas: list[float] | None = None,
) -> list[dict]:
    if lambdas is None:
        lambdas = [0, 1, 2, 3, 5, 7, 10, 15, 20, 30, 50]

    out = []
    ns = sorted({int(r["N"]) for r in rows if r["family"] in {focus_family, control_family}})
    for n in ns:
        focus = [r for r in rows if r["family"] == focus_family and int(r["N"]) == n]
        control = [r for r in rows if r["family"] == control_family and int(r["N"]) == n]
        if not focus or not control:
            continue

        # Match by rep when possible, else trunc to shortest
        focus = sorted(focus, key=lambda r: int(r["rep"]))
        control = sorted(control, key=lambda r: int(r["rep"]))
        m = min(len(focus), len(control))
        focus = focus[:m]
        control = control[:m]

        f5_focus = np.array([float(r["f5_calibrated"]) for r in focus], dtype=float)
        f5_control = np.array([float(r["f5_calibrated"]) for r in control], dtype=float)
        a_focus = np.array([float(r[action_key]) for r in focus], dtype=float)
        a_control = np.array([float(r[action_key]) for r in control], dtype=float)

        for lam in lambdas:
            score_focus = entropy_sign * beta_entropy * f5_focus + action_sign * float(lam) * a_focus
            score_control = entropy_sign * beta_entropy * f5_control + action_sign * float(lam) * a_control
            out.append(
                {
                    "N": n,
                    "lambda": float(lam),
                    "action_key": action_key,
                    "focus_family": focus_family,
                    "control_family": control_family,
                    "mean_score_focus": float(np.mean(score_focus)),
                    "mean_score_control": float(np.mean(score_control)),
                    "win_rate_focus_vs_control": hit_rate(score_focus.tolist(), score_control.tolist()),
                    "mean_f5_focus": float(np.mean(f5_focus)),
                    "mean_f5_control": float(np.mean(f5_control)),
                    "mean_action_focus": float(np.mean(a_focus)),
                    "mean_action_control": float(np.mean(a_control)),
                }
            )
    return out


def design_matrix(rows: list[dict], extra_key: str | None = None) -> np.ndarray:
    """Build intercept + N + family one-hot + optional extra predictor."""
    fams = ["Lor2D", "Lor3D", "Lor4D", "Lor5D", "KR_like"]
    n_values = sorted({int(r["N"]) for r in rows})
    n_to_idx = {n: i for i, n in enumerate(n_values[:-1])}  # reference last N
    fam_to_idx = {fam: i for i, fam in enumerate(fams[:-1])}  # reference KR_like

    cols = []
    for r in rows:
        row = [1.0]
        n = int(r["N"])
        for nv in n_values[:-1]:
            row.append(1.0 if n == nv else 0.0)
        fam = r["family"]
        for ff in fams[:-1]:
            row.append(1.0 if fam == ff else 0.0)
        if extra_key is not None:
            row.append(float(r[extra_key]))
        cols.append(row)
    return np.array(cols, dtype=float)


def ols_r2(y: np.ndarray, X: np.ndarray) -> tuple[float, np.ndarray, np.ndarray]:
    beta = np.linalg.lstsq(X, y, rcond=None)[0]
    pred = X @ beta
    ss_res = float(np.sum((y - pred) ** 2))
    ss_tot = float(np.sum((y - y.mean()) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")
    return r2, beta, pred


def main() -> int:
    ap = argparse.ArgumentParser(description="Conjecture E bridge fit between F5 and BD observables")
    ap.add_argument("--bd-actions", default="outputs_unified_functional/bd_actions.csv")
    ap.add_argument("--out-csv", default="outputs_unified_functional/conjecture_e_bridge_fit.csv")
    ap.add_argument("--out-md", default="outputs_unified_functional/conjecture_e_bridge_fit.md")
    ap.add_argument("--focus-family", default="Lor4D")
    ap.add_argument("--control-family", default="KR_like")
    args = ap.parse_args()

    path = Path(args.bd_actions)
    if not path.exists():
        raise FileNotFoundError(f"Missing {path}. Run conjecture_e_layer1_bdg_report.py first.")

    rows = load_rows(path)
    rows = [r for r in rows if r["family"] in {args.focus_family, args.control_family, "Lor2D", "Lor3D", "Lor5D"}]
    if not rows:
        raise RuntimeError("No rows loaded from bd_actions.csv")

    action_keys = ["bdg_d2_link_norm", "bdg_d2_corrected_norm", "bdg_d4_standard_norm", "bd_d4_trunc_norm", "bd_ratio"]

    # Pairwise summary statistics.
    out_rows: list[dict] = []
    for action_key in action_keys:
        xs = np.array([float(r[action_key]) for r in rows], dtype=float)
        f5 = np.array([float(r["f5_calibrated"]) for r in rows], dtype=float)
        logh = np.array([float(r["log_H"]) for r in rows], dtype=float)
        out_rows.append(
            {
                "metric": action_key,
                "spearman_f5": spearman_rank(xs, f5),
                "spearman_logH": spearman_rank(xs, logh),
                "mean_focus": float(np.mean([float(r[action_key]) for r in rows if r["family"] == args.focus_family])),
                "mean_control": float(np.mean([float(r[action_key]) for r in rows if r["family"] == args.control_family])),
            }
        )

    scan_rows: list[dict] = []
    for action_key in action_keys:
        scan_rows.extend(scan_lambda(rows, action_key, focus_family=args.focus_family, control_family=args.control_family))

    # Residual bridge: how much does a BD scalar explain F5 beyond N + family?
    bridge_rows: list[dict] = []
    y_f5 = np.array([float(r["f5_calibrated"]) for r in rows], dtype=float)
    X_base = design_matrix(rows, extra_key=None)
    r2_base, _, pred_base = ols_r2(y_f5, X_base)
    resid = y_f5 - pred_base
    for action_key in action_keys:
        X_ext = design_matrix(rows, extra_key=action_key)
        r2_ext, _, pred_ext = ols_r2(y_f5, X_ext)
        bridge_rows.append(
            {
                "metric": action_key,
                "r2_base": r2_base,
                "r2_ext": r2_ext,
                "delta_r2": r2_ext - r2_base,
                "spearman_resid": spearman_rank(np.array([float(r[action_key]) for r in rows], dtype=float), resid),
                "mean_abs_resid": float(np.mean(np.abs(resid))),
            }
        )

    out_csv = Path(args.out_csv)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(scan_rows[0].keys()))
        w.writeheader()
        w.writerows(scan_rows)

    out_md = Path(args.out_md)
    md_lines: list[str] = []
    md_lines.append("# Conjecture E bridge fit")
    md_lines.append("")
    md_lines.append(f"- Input: `{path.as_posix()}`")
    md_lines.append(f"- Output CSV: `{out_csv.as_posix()}`")
    md_lines.append("")
    md_lines.append("## Observable correlations")
    md_lines.append("")
    md_lines.append("| metric | Spearman(F5) | Spearman(log_H) | mean focus | mean control |")
    md_lines.append("|---|---:|---:|---:|---:|")
    for row in out_rows:
        md_lines.append(
            f"| {row['metric']} | {row['spearman_f5']:+.4f} | {row['spearman_logH']:+.4f} | "
            f"{row['mean_focus']:.4f} | {row['mean_control']:.4f} |"
        )

    md_lines.append("")
    md_lines.append("## Best lambda per observable")
    md_lines.append("")
    md_lines.append("| metric | best lambda | best win rate |")
    md_lines.append("|---|---:|---:|")
    for action_key in action_keys:
        sub = [r for r in scan_rows if r["action_key"] == action_key]
        best = max(sub, key=lambda r: r["win_rate_focus_vs_control"])
        md_lines.append(
            f"| {action_key} | {best['lambda']:.0f} | {best['win_rate_focus_vs_control']:.3f} |"
        )

    md_lines.append("")
    md_lines.append("## Residual bridge")
    md_lines.append("")
    md_lines.append(f"Baseline model: `F5 ~ N + family` with R² = {r2_base:.4f}")
    md_lines.append("")
    md_lines.append("| metric | R² ext | ΔR² | Spearman(metric, residual F5) |")
    md_lines.append("|---|---:|---:|---:|")
    for row in bridge_rows:
        md_lines.append(
            f"| {row['metric']} | {row['r2_ext']:.4f} | {row['delta_r2']:+.4f} | {row['spearman_resid']:+.4f} |"
        )

    md_lines.append("")
    md_lines.append("## Interpretation")
    md_lines.append("")
    md_lines.append(
        "The bridge test asks whether a BD-like scalar can improve Lorentzian-vs-KR ordering when added to the current F5 baseline. "
        "A high best win rate with O(1) lambda is the first finite-size signal that the bridge is not just a tiny perturbation."
    )

    out_md.write_text("\n".join(md_lines).rstrip() + "\n", encoding="utf-8")
    print(f"Saved: {out_csv}")
    print(f"Saved: {out_md}")

    # console summary
    for row in out_rows:
        print(
            f"{row['metric']}: Spearman(F5)={row['spearman_f5']:+.4f}, "
            f"Spearman(logH)={row['spearman_logH']:+.4f}"
        )
    print(f"Residual baseline R2(F5 ~ N + family) = {r2_base:.4f}")
    for row in bridge_rows:
        print(
            f"{row['metric']}: delta_R2={row['delta_r2']:+.4f}, "
            f"Spearman(metric,resid)={row['spearman_resid']:+.4f}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
